version: "3"
services:
  nginx:
    image: nginx
    container_name: widt-nginx
    tty: true
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - traefik-public2
  redis:
    image: redis:alpine
    container_name: widt-redis
    ports:
      - "6379:6379"
    networks:
      - traefik-public2
  app:
    container_name: widt-app
    image: node:18.1.0-alpine
    # image: timbru31/node-alpine-git
    working_dir: /app
    command: sh -c "yarn install && yarn app"
    networks:
      - traefik-public2
    expose:
      - 80
      - 2224
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  db:
    image: mariadb
    container_name: widt-mariadb
    restart: on-failure
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./:/data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: database
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - traefik-public2
networks:
  traefik-public2:
    name: traefik-public2
