version: "3"
services:
  nginx:
    image: nginx
    container_name: widt-nginx
    tty: true
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - /data/videos:/data/videos
    networks:
      - traefik-public2
  redis:
    image: redis:alpine
    container_name: widt-redis
    ports:
      - "6379:6379"
    networks:
      - traefik-public2
  bot:
    # image: python:3.10.13-alpine3.18
    image: pytorch/pytorch:latest
    container_name: bot
    ports:
      - 5001:5000
    volumes:
      - ./../wieisdetrol-bot:/app
    working_dir: /app
    command: sh -c "pip3 install -r requirements.txt && python run.py"
    networks:
      - traefik-public2
  backendapp:
    container_name: widt-app
    image: node:18.1.0-alpine
    # image: timbru31/node-alpine-git
    working_dir: /app
    command: sh -c "yarn install && yarn app"
    networks:
      - traefik-public2
    expose:
      - 80
      - 2224
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  db:
    image: mariadb
    container_name: widt-mariadb
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./:/data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: database
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - traefik-public2
  adminer:
    image: adminer
    restart: always
    ports:
      - 5555:8080
    networks:
      - traefik-public2
networks:
  traefik-public2:
    name: traefik-public2
