apiVersion: v1
data:
  nginx.conf: |
    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }
    
    upstream backendapp {
      server backendapp:80;
    }    
    server {
      listen 80;
      
      location / {
        proxy_pass http://backendapp/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
      }
      location /videos/ {
        alias /data/videos/;
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  name: nginx-config
  namespace: wieisdetrol
  labels:
    io.kompose.service: nginx
