apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: backendapp
  name: pvc-backendapp
  namespace: wieisdetrol
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
