apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: bot
  name: pvc-bot-site-packages
  namespace: wieisdetrol
spec:
  storageClassName: nutanix-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
